#Eureka服务器配置
eureka:
  instance:
    hostname: @eureka-ip@
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:   http://@eureka-ip@:@eureka-port@/eureka/
